language: go

go:
  - 1.9

resources:
  - name: aws_pack_creds
    type: integration
    integration: "dr_aws"

jobs:
  - name: sample_pipelines_terraform_runCI #this has to be the name, not customizable
    type: runCI
    steps:
      - IN: aws_pack_creds
      - TASK:
          name: build_ci
          script:
            - export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_pack_creds "accessKey")
            - export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_pack_creds "secretKey")
            - echo $AWS_ACCESS_KEY_ID
            - echo $AWS_SECRET_ACCESS_KEY
    on_success:
      script:
        - echo "Done!!"
